# Generated by Django 2.0.2 on 2018-03-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlydeposit',
            options={'verbose_name': 'Pagamento Mensal Obrigatório', 'verbose_name_plural': 'Pagamentos Mensais Obrigatórios'},
        ),
    ]
