# Generated by Django 2.0.2 on 2018-02-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='who_did_it',
            field=models.CharField(default='Desconhecido', max_length=257),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='justification',
            field=models.CharField(default='Sem Descrição', max_length=257),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, default=-666, max_digits=6),
        ),
    ]
