# Generated by Django 2.0.2 on 2018-02-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0002_auto_20180216_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.CharField(default='Comida', max_length=257),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(default='Geral', max_length=257),
        ),
    ]
