# Generated by Django 2.0.2 on 2018-02-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0003_auto_20180216_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='origin',
        ),
    ]
