# Generated by Django 2.0.2 on 2018-02-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0004_auto_20180216_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination',
            field=models.CharField(default='Caixa Não Informada', max_length=257),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.CharField(default='Caixa Não Informada', max_length=257),
        ),
    ]
