# Generated by Django 2.0.2 on 2018-02-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0006_auto_20180217_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(blank=True, default='Caixa Não Informada', max_length=257, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin',
            field=models.CharField(blank=True, default='Caixa Não Informada', max_length=257, null=True),
        ),
    ]
