# Generated by Django 2.0.2 on 2018-02-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0007_auto_20180217_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes'),
        ),
    ]
