# Generated by Django 2.0.2 on 2018-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0008_transaction_comprovante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='who_did_it',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=257, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='justification',
            field=models.CharField(default='', max_length=257),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=257, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
