# Generated by Django 2.0.2 on 2018-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0009_auto_20180217_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='who_did_it',
            field=models.CharField(default='', max_length=257),
        ),
    ]
