# Generated by Django 2.0.2 on 2018-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0010_transaction_who_did_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(default='', max_length=257),
        ),
    ]
