# Generated by Django 2.0.2 on 2018-02-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0011_transaction_type_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type_transaction',
            new_name='its_type',
        ),
    ]
