# Generated by Django 2.0.2 on 2018-02-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0012_auto_20180217_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='comprovante',
            new_name='receipt',
        ),
    ]
