# Generated by Django 2.0.2 on 2018-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0013_auto_20180217_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
