# Generated by Django 2.0.2 on 2018-03-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0013_auto_20180217_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'boxes',
            },
        ),
    ]
