# Generated by Django 2.0.2 on 2018-03-11 15:42

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('varys', '0014_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=257)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('justification', models.CharField(default='', max_length=257)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.CharField(default='', max_length=257)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='comprovantes')),
                ('its_type', models.CharField(default='', max_length=257)),
                ('who_paid', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
