# Generated by Django 2.0.2 on 2018-03-14 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('varys', '0015_grouptransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptransaction',
            name='who_paid',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name': 'Caixinha', 'verbose_name_plural': 'Caixinhas'},
        ),
        migrations.AddField(
            model_name='box',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='box',
            name='justification',
            field=models.CharField(default='', max_length=257, verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='box',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
        migrations.DeleteModel(
            name='GroupTransaction',
        ),
    ]
